### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by tbm**

### CODE REVIEW

**Comment by redstreet** [comment]
Thanks!

**Comment by redstreet** [comment]
Yikes, I picked the "squash and commit" option and apparently that creates a new commit with me as the author. Sorry, didn't mean to not give credit where credit is due. I'll pick the merge option next time.

**Comment by tbm** [comment]
No problem. I have some other patches coming.

I think the best way to merge is the "merge and rebase" option.  That doesn't create the annoying merge commits, preserves the author (I stay author, you become the commiter)

**Comment by redstreet** [comment]
Thanks, that helps to know, will do in the future.

**Comment by redstreet** [comment]
Sure, I'm happy to review them.

**Pull request merged**
